# Generated by Django 3.2.9 on 2021-11-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bill',
        ),
    ]
