# Generated by Django 3.2.9 on 2021-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0002_remove_student_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bill',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
