# Generated by Django 3.2.9 on 2021-11-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0003_student_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bill',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.student')),
            ],
        ),
    ]
