# Generated by Django 3.2.9 on 2021-11-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0004_auto_20211116_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
