# Generated by Django 3.2.9 on 2021-11-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0005_alter_studentclass_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='name',
            field=models.CharField(default='Science', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course'),
        ),
    ]
