# Generated by Django 3.2.9 on 2021-11-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0006_auto_20211116_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.student'),
        ),
    ]
