# Generated by Django 3.2.9 on 2021-11-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0007_alter_studentclass_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollmentSummary',
        ),
        migrations.RemoveField(
            model_name='course',
            name='gradeReport',
        ),
        migrations.AddField(
            model_name='enrollmentsummary',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradereport',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course'),
            preserve_default=False,
        ),
    ]
