# Generated by Django 3.2.9 on 2021-11-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0008_auto_20211116_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsummary',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrollmentsummary',
            name='report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
