# Generated by Django 3.2.9 on 2021-11-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0009_auto_20211116_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.student'),
        ),
        migrations.AlterField(
            model_name='droprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.student'),
        ),
    ]
