# Generated by Django 3.2.9 on 2021-11-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0011_alter_course_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='registrationsystem.student'),
        ),
    ]
